export const sitePages = [
  {
    title: "Home",
    path: "/",
    source_url: "https://hortsoc.org/",
    migration_status: "migrated",
    content_file: "src/content/pages/home.md",
    notes: "Migrated into Markdown from the published WordPress export.",
  },
  {
    title: "The 127th Annual Show",
    path: "/2017/07/01/summer-newsletter/",
    source_url: "https://hortsoc.org/2017/07/01/summer-newsletter/",
    migration_status: "migrated",
    content_file: "src/content/pages/summer-newsletter.md",
    notes: "Migrated into Markdown from the published WordPress export.",
  },
  {
    title: "LITTLE GREEN FINGERS",
    path: "/2017/08/09/little-green-fingers/",
    source_url: "https://hortsoc.org/2017/08/09/little-green-fingers/",
    migration_status: "migrated",
    content_file: "src/content/pages/little-green-fingers.md",
    notes: "Migrated into Markdown from the published WordPress export.",
  },
  {
    title: "From the Pumpkin Patch",
    path: "/2017/09/05/from-the-pumpkin-patch/",
    source_url: "https://hortsoc.org/2017/09/05/from-the-pumpkin-patch/",
    migration_status: "migrated",
    content_file: "src/content/pages/from-the-pumpkin-patch.md",
    notes: "Migrated into Markdown from the published WordPress export.",
  },
  {
    title: "Metaldehyde slug pellets banned",
    path: "/2019/02/11/metaldehyde-slug-pellets-banned/",
    source_url: "https://hortsoc.org/2019/02/11/metaldehyde-slug-pellets-banned/",
    migration_status: "migrated",
    content_file: "src/content/pages/metaldehyde-slug-pellets-banned.md",
    notes: "Migrated into Markdown from the published WordPress export.",
  },
  {
    title: "Queen's Award for Voluntary Service",
    path: "/2019/06/03/963/",
    source_url: "https://hortsoc.org/2019/06/03/963/",
    migration_status: "migrated",
    content_file: "src/content/pages/queen-award-for-voluntary-service.md",
    notes: "Migrated into Markdown from the published WordPress export with a conservatively inferred title because the source post title was blank.",
  },
  {
    title: "OCTOBER Seasonal Tips",
    path: "/2020/01/01/april-seasonal-tips/",
    source_url: "https://hortsoc.org/2020/01/01/april-seasonal-tips/",
    migration_status: "migrated",
    content_file: "src/content/pages/april-seasonal-tips.md",
    notes: "Migrated into Markdown from the published WordPress export.",
  },
  {
    title: "About",
    path: "/about/",
    source_url: "https://hortsoc.org/about/",
    migration_status: "migrated",
    content_file: "src/content/pages/about.md",
    notes: "Migrated into Markdown from the published WordPress export.",
  },
  {
    title: "Annual Show",
    path: "/annual-show/",
    source_url: "https://hortsoc.org/annual-show/",
    migration_status: "migrated",
    content_file: "src/content/pages/annual-show.md",
    notes: "Migrated into Markdown from the published WordPress export.",
  },
  {
    title: "Blog",
    path: "/blog/",
    source_url: "https://hortsoc.org/blog/",
    migration_status: "migrated",
    content_file: "src/content/pages/blog.md",
    notes: "Migrated into Markdown from the published WordPress export.",
  },
  {
    title: "CONTACTS",
    path: "/contacts/",
    source_url: "https://hortsoc.org/contacts/",
    migration_status: "migrated",
    content_file: "src/content/pages/contacts.md",
    notes: "Migrated into Markdown from the published WordPress export.",
  },
  {
    title: "Gallery",
    path: "/gallery/",
    source_url: "https://hortsoc.org/gallery/",
    migration_status: "migrated",
    content_file: "src/content/pages/gallery.md",
    notes: "Gallery landing page migrated from the WordPress export into an index of structured event galleries; legacy attachment URLs remain redirect-only.",
  },
  {
    title: "Annual Show 2024",
    path: "/gallery/annual-show-2024/",
    source_url: "https://hortsoc.org/gallery/",
    migration_status: "migrated",
    content_file: "src/content/pages/gallery-annual-show-2024.md",
    notes: "Dedicated gallery event page split from the original WordPress Gallery landing page; legacy attachment URLs remain redirect-only.",
  },
  {
    title: "Annual Show 2023",
    path: "/gallery/annual-show-2023/",
    source_url: "https://hortsoc.org/gallery/",
    migration_status: "migrated",
    content_file: "src/content/pages/gallery-annual-show-2023.md",
    notes: "Dedicated gallery event page split from the original WordPress Gallery landing page; legacy attachment URLs remain redirect-only.",
  },
  {
    title: "Annual Show 2022",
    path: "/gallery/annual-show-2022/",
    source_url: "https://hortsoc.org/gallery/",
    migration_status: "migrated",
    content_file: "src/content/pages/gallery-annual-show-2022.md",
    notes: "Dedicated gallery event page split from the original WordPress Gallery landing page; legacy attachment URLs remain redirect-only.",
  },
  {
    title: "Annual Show 2021",
    path: "/gallery/annual-show-2021/",
    source_url: "https://hortsoc.org/gallery/",
    migration_status: "migrated",
    content_file: "src/content/pages/gallery-annual-show-2021.md",
    notes: "Dedicated gallery event page split from the original WordPress Gallery landing page; legacy attachment URLs remain redirect-only.",
  },
  {
    title: "Plant Sale 2021",
    path: "/gallery/plant-sale-2021/",
    source_url: "https://hortsoc.org/gallery/",
    migration_status: "migrated",
    content_file: "src/content/pages/gallery-plant-sale-2021.md",
    notes: "Dedicated gallery event page split from the original WordPress Gallery landing page; legacy attachment URLs remain redirect-only.",
  },
  {
    title: "Membership",
    path: "/membership/",
    source_url: "https://hortsoc.org/membership/",
    migration_status: "migrated",
    content_file: "src/content/pages/membership.md",
    notes: "Migrated into Markdown from the published WordPress export.",
  },
  {
    title: "Thing one",
    path: "/portfolio/thing-one/",
    source_url: "https://hortsoc.org/portfolio/thing-one/",
    migration_status: "migrated",
    content_file: "src/content/pages/thing-one.md",
    notes: "Migrated into Markdown from the published WordPress export.",
  },
  {
    title: "Schools Liaison",
    path: "/schools-liaison/",
    source_url: "https://hortsoc.org/schools-liaison/",
    migration_status: "migrated",
    content_file: "src/content/pages/schools-liaison.md",
    notes: "Migrated into Markdown from the published WordPress export.",
  },
  {
    title: "Plant Sale Poster",
    path: "/testimonial/872/",
    source_url: "https://hortsoc.org/testimonial/872/",
    migration_status: "migrated",
    content_file: "src/content/pages/testimonial-872.md",
    notes: "Migrated into Markdown from the published WordPress export with a title inferred from the poster image because the source title was blank.",
  },
  {
    title: "Ruth Rooley Chairman",
    path: "/testimonial/ruth-rooley-chairman/",
    source_url: "https://hortsoc.org/testimonial/ruth-rooley-chairman/",
    migration_status: "migrated",
    content_file: "src/content/pages/ruth-rooley-chairman.md",
    notes: "Migrated into Markdown from the published WordPress export while preserving the legacy custom-post-type route.",
  },
  {
    title: "Tree Planting",
    path: "/tree-planting/",
    source_url: "https://hortsoc.org/tree-planting/",
    migration_status: "migrated",
    content_file: "src/content/pages/tree-planting.md",
    notes: "Migrated into Markdown from the published WordPress export; legacy tree-planting child attachment routes now redirect directly to their media files instead of remaining as canonical pages.",
  },
  {
    title: "What's On",
    path: "/whats-on/",
    source_url: "https://hortsoc.org/whats-on/",
    migration_status: "migrated",
    content_file: "src/content/pages/whats-on.md",
    notes: "Migrated into Markdown from the published WordPress export.",
  },
  {
    title: "Who's Who",
    path: "/whoswho/",
    source_url: "https://hortsoc.org/whoswho/",
    migration_status: "migrated",
    content_file: "src/content/pages/whoswho.md",
    notes: "Migrated into Markdown from the published WordPress export.",
  },
  {
    title: "Winners 2021",
    path: "/winners-2021/",
    source_url: "https://hortsoc.org/winners-2021/",
    migration_status: "migrated",
    content_file: "src/content/pages/winners-2021.md",
    notes: "Migrated into Markdown from the published WordPress export.",
  },
];

export function pathToSlugParams(path) {
  const slug = path.split("/").filter(Boolean).join("/");
  return slug || undefined;
}
